name: 'Node'

on:
  push:


jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: 'step - hello world'
        run: echo "hello world"

      - name: 'step - checkout'
        uses: actions/checkout@v4

      - name: 'step - setup node'
        uses: actions/setup-node@v4
        with:
          node-version: 20
        
      - name: 'step - dependencies'
        run: npm ci

      - name: 'step - build'
        run: npm i

      - name: 'step - test'
        run: npm run test
          
